trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- bash: |
    echo "AZ-400 Pi5 DevOps Lab"
    echo "Hostname:"
    hostname

    echo "Architectuur:"
    uname -m

    echo "OS:"
    cat /etc/os-release

  displayName: 'Controle Raspberry Pi'