services:

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"

    volumes:
      - /srv/pi5-lab/adguard/work:/opt/adguardhome/work
      - /srv/pi5-lab/adguard/conf:/opt/adguardhome/conf
      - /srv/pi5-lab/certs/adguard:/certs:ro
      - /srv/pi5-lab/certs/nginx:/certs-nginx
    networks:
      - default


  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - /srv/pi5-lab/step-ca:/home/step

    networks:
      default:
        aliases:
          - ca.home.arpa


  step-client:
    image: smallstep/step-cli:latest
    container_name: step-client
    restart: "no"

    volumes:
      - /srv/pi5-lab/step-ca/certs:/home/step/ca-certs:ro
      - /srv/pi5-lab/step-ca/secrets:/home/step/secrets:ro
      - /srv/pi5-lab/certs/adguard:/certs
      - /srv/pi5-lab/certs/nginx:/certs-nginx
    networks:
      - default


  ntopng:
    image: ntop/ntopng_arm64.dev:latest
    container_name: ntopng
    restart: unless-stopped

    network_mode: host

    volumes:
      - /srv/pi5-lab/ntopng:/var/lib/ntopng

    command:
      - "-i"
      - "eth0"


networks:
  default:
    name: pi5-lab
