services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"

    volumes:
      - /srv/pi5-lab/adguard/work:/opt/adguardhome/work
      - /srv/pi5-lab/adguard/conf:/opt/adguardhome/conf
